[package]
name = "rust_solutions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array_tool = "1.0.0"
itertools = "0.10.5"
anyhow = "1.0.66"

[profile.release]
opt-level = 3 

